#pragma once

#ifndef PBUILD_H
#define PBUILD_H

#define PICASSO_MAJOR_VERSION 2024
#define PICASSO_MINOR_VERSION 1
#define PICASSO_PATCH_VERSION 0

#define PICASSO_LINUX_BUILD 1
#define PICASSO_DEBUG_ENABLE 1

#define PICASSO_FRAME_MS_LIMIT 16.7 // 60 fps

#endif