#pragma once

#ifndef PBUILD_H
#define PBUILD_H

#define PICASSO_MAJOR_VERSION 2024
#define PICASSO_MINOR_VERSION 1
#define PICASSO_PATCH_VERSION 0
#define PICASSO_DEFAULT_WIDTH 800
#define PICASSO_DEFAULT_HEIGHT 600

#define PICASSO_LINUX_BUILD 1
#define PICASSO_VULKAN_BUILD 1

// DEBUG PARAMS
#define PICASSO_DEBUG_ENABLE 1

#define PICASSO_FRAME_MS_LIMIT 16.7 // 60 fps

// drivers
#define PICASSO_VULKAN_MIN_TRANSFER_SCORE 255

#endif